apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: release
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: webfrontendchart
    app.kubernetes.io/version: v1
    helm.sh/chart: webfrontendchart-0.1.0
  name: release-webfrontendchart
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: release
      app.kubernetes.io/name: webfrontendchart
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: release
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: webfrontendchart
        app.kubernetes.io/version: v1
        helm.sh/chart: webfrontendchart-0.1.0
    spec:
      containers:
      - image: amyacr.azurecr.io/webfrontend:v1
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /
            port: http
        name: webfrontendchart
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /
            port: http
        resources: {}
        securityContext:
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
          seccompProfile:
            type: RuntimeDefault
      securityContext: {}
      serviceAccountName: release-webfrontendchart
